# Generated by Django 2.1.2 on 2018-12-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='igss_users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('user_email', models.CharField(max_length=250)),
                ('Dept_id', models.IntegerField()),
                ('user_type', models.IntegerField()),
            ],
        ),
    ]
