# Generated by Django 2.1.2 on 2018-12-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='igss_users',
            new_name='IgsrUser',
        ),
    ]
