# Generated by Django 2.1.2 on 2018-12-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0002_auto_20181209_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgenda',
            fields=[
                ('Agenda_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Agenda_date', models.DateField()),
                ('agenda_title', models.CharField(max_length=250)),
                ('agenda_state_Id', models.CharField(max_length=250)),
                ('Dept_id', models.IntegerField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.IgsrUser')),
            ],
        ),
    ]
