# Generated by Django 2.1.2 on 2018-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0004_auto_20181211_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_type',
            fields=[
                ('Type_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
    ]
