# Generated by Django 2.1.2 on 2018-12-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0005_users_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igsruser',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.Users_type'),
        ),
    ]
