# Generated by Django 2.1.2 on 2018-12-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0006_auto_20181212_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='igsruser',
            name='Dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.Deparments'),
        ),
        migrations.AlterField(
            model_name='meetingagenda',
            name='Dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.Deparments'),
        ),
    ]
