# Generated by Django 2.1.2 on 2018-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0007_auto_20181212_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_State',
            fields=[
                ('State_id', models.AutoField(primary_key=True, serialize=False)),
                ('State_type', models.CharField(max_length=250)),
            ],
        ),
    ]
