# Generated by Django 2.1.2 on 2018-12-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0009_auto_20181212_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('actions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_title', models.CharField(max_length=100)),
                ('Item_subject', models.CharField(max_length=250)),
                ('Agenda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.MeetingAgenda')),
                ('Item_action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igss_app.Actions')),
            ],
        ),
    ]
