# Generated by Django 2.1.2 on 2018-12-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igss_app', '0010_actions_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingagenda',
            name='item_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='igss_app.Items'),
        ),
    ]
